-- DROP TABLE EMPLOYEE IF EXISTS;

CREATE TABLE EMPLOYEE (
    EMP_ID INTEGER IDENTITY NOT NULL,
    FNAME VARCHAR,
    LNAME VARCHAR,
    EMAIL VARCHAR(100),
    TITLE VARCHAR(100),
    SALARY DOUBLE,
    VERSION INTEGER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    ADDR_ID INTEGER,
    PRIMARY KEY (EMP_ID)
);

-- DROP TABLE ADDRESS IF EXISTS;

CREATE TABLE ADDRESS (
    ADDR_ID INTEGER IDENTITY NOT NULL,
    CITY VARCHAR,
    COUNTRY VARCHAR,
    POSTAL VARCHAR,
    STATE VARCHAR,
    STREET VARCHAR,
    VERSION INTEGER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (ADDR_ID)
);

-- DROP TABLE PHONE IF EXISTS;

CREATE TABLE PHONE (
    PHONE_ID INTEGER IDENTITY NOT NULL,
    AREACODE VARCHAR,
    PHONENUMBER VARCHAR,
    PHONE_TYPE VARCHAR,
    VERSION INTEGER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    OWNING_EMP_ID INTEGER,
    PRIMARY KEY (PHONE_ID)
);

-- DROP TABLE EMP_PROJ IF EXISTS;
-- DROP TABLE PROJECT IF EXISTS;

CREATE TABLE PROJECT (
    PROJ_ID INTEGER IDENTITY NOT NULL,
    DESCRIPTION VARCHAR,
    NAME VARCHAR,
    VERSION INTEGER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (PROJ_ID)
);

CREATE TABLE EMP_PROJ (
    EMP_ID INTEGER NOT NULL,
    PROJ_ID INTEGER NOT NULL,
    PRIMARY KEY (EMP_ID, PROJ_ID)
);

ALTER TABLE
    EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_ADDR_ID FOREIGN KEY (ADDR_ID) REFERENCES ADDRESS(ADDR_ID);
ALTER TABLE
    PHONE ADD CONSTRAINT FK_PHONE_OWNING_EMP_ID FOREIGN KEY (OWNING_EMP_ID) REFERENCES EMPLOYEE(EMP_ID);
ALTER TABLE
    EMP_PROJ ADD CONSTRAINT FK_EMP_PROJ_PROJ_ID FOREIGN KEY (PROJ_ID) REFERENCES PROJECT(PROJ_ID);
ALTER TABLE
    EMP_PROJ ADD CONSTRAINT FK_EMP_PROJ_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID);

-- DROP TABLE EMPLOYEE_TASKS;

CREATE TABLE 
    EMPLOYEE_TASKS (OWNING_EMP_ID INTEGER NOT NULL,
    TASK_DESCRIPTION VARCHAR(100),
    TASK_START TIMESTAMP,
    TASK_END_DATE TIMESTAMP,
    TASK_DONE BOOLEAN
);
ALTER TABLE
    EMPLOYEE_TASKS ADD CONSTRAINT FK_OWNING_EMP_ID_EMP_ID FOREIGN KEY(OWNING_EMP_ID) REFERENCES EMPLOYEE(EMP_ID);

-- DROP TABLE HPHONE

CREATE TABLE HPHONE (
    PHONE_ID INTEGER NOT NULL,
    MAP_COORDS VARCHAR(100),
    PRIMARY KEY (PHONE_ID),
    CONSTRAINT FK_HPHONE_PHONE_ID FOREIGN KEY (PHONE_ID) REFERENCES PHONE(PHONE_ID)
);

-- DROP TABLE MPHONE

CREATE TABLE MPHONE (
    PHONE_ID INTEGER NOT NULL,
    PROVIDER VARCHAR,
    PRIMARY KEY (PHONE_ID),
    CONSTRAINT FK_MPHONE_PHONE_ID FOREIGN KEY (PHONE_ID) REFERENCES PHONE(PHONE_ID)
);

-- DROP TABLE WPHONE

CREATE TABLE WPHONE (
    PHONE_ID INTEGER NOT NULL,
    DEPARTMENT VARCHAR,
    PRIMARY KEY (PHONE_ID),
    CONSTRAINT FK_WPHONE_PHONE_ID FOREIGN KEY (PHONE_ID) REFERENCES PHONE(PHONE_ID)
);